name: proseva
services:
  #
  # core backend services
  #
  lisiting-microservice:
    image: lisiting-microservice
    build:
      context: "microservices/listing"
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - MY_UID=${MY_UID}
        - MY_USERNAME=${MY_USERNAME}
        - MY_GID=${MY_GID}
        - MY_GROUP=${MY_GROUP}
    hostname: mbansari.proseva.in
    container_name: listing-microservice
    depends_on:
      infra-keycloak:
        condition: service_healthy
      listing-db:
        condition: service_healthy
        # restart: true # TODO: restart is not support in current version. [upgrade docker-engine] 
    # volumes:
    #   - ./configs/nginx/ssl/proseva.crt:/usr/local/share/ca-certificates/proseva.crt:ro
    # extra_hosts:
    #   - "keycloak.proseva.net:host-gateway"
    networks:
      - private-net
    # healthcheck: # TODO: define health-check route..
  #
  # databases
  #
  listing-db:
    image: postgres:17.4-alpine
    container_name: listing-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${LISTING_DB_USER}
      - POSTGRES_PASSWORD=${LISTING_DB_PASSWORD}
      - POSTGRES_DB=listing
    volumes:
      - db-listing-vol:/var/lib/postgresql/data
    networks:
      - private-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LISTING_DB_USER} -d listing"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  #
  # prerequisites
  #
  infra-keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: infra-keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=proseva@2025
      - KC_PROXY=edge
      - KC_HEALTH_ENABLED=true
    command:
      - start-dev
      - --hostname=https://keycloak.proseva.net
      - --hostname-strict=true
    volumes:
      - keycloak-data:/opt/keycloak/data/
    networks:
      - private-net
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  infra-reverse-proxy:
    image: nginx:1.14.2
    container_name: infra-reverse-proxy
    ports:
      - 443:443
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./configs/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - lisiting-microservice
      - infra-keycloak
    networks:
      - private-net
volumes:
  #
  # database volumes
  #
  db-listing-vol:
    driver: local
  keycloak-data:
    driver: local
networks:
  private-net:
    name: proseva-private-net
    driver_opts:
      com.docker.network.bridge.name: br-proseva
    ipam:
      config:
        - subnet: ${PROSEVA_PRIVATE_NET}
