[tool.poetry]
name = "listing"
version = "0.1.0"
description = ""
authors = ["Mohammed Bilal Ansari <mohammedbilalansari.321@gmail.com>"]
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.12"
pydantic = "^2.10.6"
alembic = "^1.15.2"
mscore = { git = "https://github.com/bilalsp/proseva.git", subdirectory = "libs/mscore", rev="915e143" } # TODO: use either tag or rev
# mscore = {git = "git@github.com:bilalsp/proseva.git", subdirectory = "libs/mscore"}
# mscore = {path = "../../libs/mscore", develop = true}
uvicorn = "^0.27.1"
gunicorn = "^23.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.0"
ruff = "^0.2.1"
mypy = "^1.9.0"

[tool.poetry.scripts]
listing-service = "listing.__main__:runserver"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
